# basic options,  I can say what ever here
title: Megan's awesome-blog
author: meganhsu2250
email: your-email@domain.com
description: A lovely wonderful blog
twitter_username: meganhsu2250
github_username:  meganhsu2250

# Build settings
markdown: kramdown
theme: jekyll-theme-merlot
